baseURL = "https://aymericgerardin.github.io/hugo-toast/exampleSite/"
languageCode = "en-US"
title = "My Toast club"
theme = "hugo-toast"

[params]
    name = "My Hugo Toast club"
    description = "Awsome club"
    email = "contact@hugoToast.com"
    address = "9127 S Jamaica St, Englewood, CO 80112, USA"
    year = 2019
    logo = "images/toastmasters_blue.png"
	serviceTitle = "Sign in!"
    background = ""
    favicon = "images/Favicon.ico"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
	showWhere = true
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false
	footerEnableMailChimpWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[params.social]]
	title = "facebook"
	url = "https://facebook.com/nickname"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "email"
	url = "mailto:email"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"